name: BonusXP
version: 0.0.2
main: com.massivecraft.bonusxp.BonusXP
authors: [yendor46]
description: BonusXP provides mcMMO XP bonuses of 5%, 10%, 15%, 20%, 25%, 30%, 35%, 40% or 45% based on the highest permission enabled. This supplements the mcMMO permissions that begin at 50%.  
depend: [mcMMO, mcore]
# -------------------------------------------- #
# THE REAL NODES
# -------------------------------------------- #
permissions:
  bonusxp.percent5.acrobatics: {description: 5% mcMMO XP bonus, default: false}
  bonusxp.percent5.archery: {description: 5% mcMMO XP bonus, default: false}
  bonusxp.percent5.axes: {description: 5% mcMMO XP bonus, default: false}
  bonusxp.percent5.excavation: {description: 5% mcMMO XP bonus, default: false}
  bonusxp.percent5.fishing: {description: 5% mcMMO XP bonus, default: false}
  bonusxp.percent5.herbalism: {description: 5% mcMMO XP bonus, default: false}
  bonusxp.percent5.mining: {description: 5% mcMMO XP bonus, default: false}
  bonusxp.percent5.repair: {description: 5% mcMMO XP bonus, default: false}
  bonusxp.percent5.smelting: {description: 5% mcMMO XP bonus, default: false}
  bonusxp.percent5.swords: {description: 5% mcMMO XP bonus, default: false}
  bonusxp.percent5.taming: {description: 5% mcMMO XP bonus, default: false}
  bonusxp.percent5.unarmed: {description: 5% mcMMO XP bonus, default: false}
  bonusxp.percent5.woodcutting: {description: 5% mcMMO XP bonus, default: false}
  bonusxp.percent10.acrobatics: {description: 10% mcMMO XP bonus, default: false}
  bonusxp.percent10.archery: {description: 10% mcMMO XP bonus, default: false}
  bonusxp.percent10.axes: {description: 10% mcMMO XP bonus, default: false}
  bonusxp.percent10.excavation: {description: 10% mcMMO XP bonus, default: false}
  bonusxp.percent10.fishing: {description: 10% mcMMO XP bonus, default: false}
  bonusxp.percent10.herbalism: {description: 10% mcMMO XP bonus, default: false}
  bonusxp.percent10.mining: {description: 10% mcMMO XP bonus, default: false}
  bonusxp.percent10.repair: {description: 10% mcMMO XP bonus, default: false}
  bonusxp.percent10.smelting: {description: 10% mcMMO XP bonus, default: false}
  bonusxp.percent10.swords: {description: 10% mcMMO XP bonus, default: false}
  bonusxp.percent10.taming: {description: 10% mcMMO XP bonus, default: false}
  bonusxp.percent10.unarmed: {description: 10% mcMMO XP bonus, default: false}
  bonusxp.percent10.woodcutting: {description: 10% mcMMO XP bonus, default: false}
  bonusxp.percent15.acrobatics: {description: 15% mcMMO XP bonus, default: false}
  bonusxp.percent15.archery: {description: 15% mcMMO XP bonus, default: false}
  bonusxp.percent15.axes: {description: 15% mcMMO XP bonus, default: false}
  bonusxp.percent15.excavation: {description: 15% mcMMO XP bonus, default: false}
  bonusxp.percent15.fishing: {description: 15% mcMMO XP bonus, default: false}
  bonusxp.percent15.herbalism: {description: 15% mcMMO XP bonus, default: false}
  bonusxp.percent15.mining: {description: 15% mcMMO XP bonus, default: false}
  bonusxp.percent15.repair: {description: 15% mcMMO XP bonus, default: false}
  bonusxp.percent15.smelting: {description: 15% mcMMO XP bonus, default: false}
  bonusxp.percent15.swords: {description: 15% mcMMO XP bonus, default: false}
  bonusxp.percent15.taming: {description: 15% mcMMO XP bonus, default: false}
  bonusxp.percent15.unarmed: {description: 15% mcMMO XP bonus, default: false}
  bonusxp.percent15.woodcutting: {description: 15% mcMMO XP bonus, default: false}
  bonusxp.percent20.acrobatics: {description: 20% mcMMO XP bonus, default: false}
  bonusxp.percent20.archery: {description: 20% mcMMO XP bonus, default: false}
  bonusxp.percent20.axes: {description: 20% mcMMO XP bonus, default: false}
  bonusxp.percent20.excavation: {description: 20% mcMMO XP bonus, default: false}
  bonusxp.percent20.fishing: {description: 20% mcMMO XP bonus, default: false}
  bonusxp.percent20.herbalism: {description: 20% mcMMO XP bonus, default: false}
  bonusxp.percent20.mining: {description: 20% mcMMO XP bonus, default: false}
  bonusxp.percent20.repair: {description: 20% mcMMO XP bonus, default: false}
  bonusxp.percent20.smelting: {description: 20% mcMMO XP bonus, default: false}
  bonusxp.percent20.swords: {description: 20% mcMMO XP bonus, default: false}
  bonusxp.percent20.taming: {description: 20% mcMMO XP bonus, default: false}
  bonusxp.percent20.unarmed: {description: 20% mcMMO XP bonus, default: false}
  bonusxp.percent20.woodcutting: {description: 20% mcMMO XP bonus, default: false}
  bonusxp.percent25.acrobatics: {description: 25% mcMMO XP bonus, default: false}
  bonusxp.percent25.archery: {description: 25% mcMMO XP bonus, default: false}
  bonusxp.percent25.axes: {description: 25% mcMMO XP bonus, default: false}
  bonusxp.percent25.excavation: {description: 25% mcMMO XP bonus, default: false}
  bonusxp.percent25.fishing: {description: 25% mcMMO XP bonus, default: false}
  bonusxp.percent25.herbalism: {description: 25% mcMMO XP bonus, default: false}
  bonusxp.percent25.mining: {description: 25% mcMMO XP bonus, default: false}
  bonusxp.percent25.repair: {description: 25% mcMMO XP bonus, default: false}
  bonusxp.percent25.smelting: {description: 25% mcMMO XP bonus, default: false}
  bonusxp.percent25.swords: {description: 25% mcMMO XP bonus, default: false}
  bonusxp.percent25.taming: {description: 25% mcMMO XP bonus, default: false}
  bonusxp.percent25.unarmed: {description: 25% mcMMO XP bonus, default: false}
  bonusxp.percent25.woodcutting: {description: 25% mcMMO XP bonus, default: false}
  bonusxp.percent30.acrobatics: {description: 30% mcMMO XP bonus, default: false}
  bonusxp.percent30.archery: {description: 30% mcMMO XP bonus, default: false}
  bonusxp.percent30.axes: {description: 30% mcMMO XP bonus, default: false}
  bonusxp.percent30.excavation: {description: 30% mcMMO XP bonus, default: false}
  bonusxp.percent30.fishing: {description: 30% mcMMO XP bonus, default: false}
  bonusxp.percent30.herbalism: {description: 30% mcMMO XP bonus, default: false}
  bonusxp.percent30.mining: {description: 30% mcMMO XP bonus, default: false}
  bonusxp.percent30.repair: {description: 30% mcMMO XP bonus, default: false}
  bonusxp.percent30.smelting: {description: 30% mcMMO XP bonus, default: false}
  bonusxp.percent30.swords: {description: 30% mcMMO XP bonus, default: false}
  bonusxp.percent30.taming: {description: 30% mcMMO XP bonus, default: false}
  bonusxp.percent30.unarmed: {description: 30% mcMMO XP bonus, default: false}
  bonusxp.percent30.woodcutting: {description: 30% mcMMO XP bonus, default: false}
  bonusxp.percent35.acrobatics: {description: 35% mcMMO XP bonus, default: false}
  bonusxp.percent35.archery: {description: 35% mcMMO XP bonus, default: false}
  bonusxp.percent35.axes: {description: 35% mcMMO XP bonus, default: false}
  bonusxp.percent35.excavation: {description: 35% mcMMO XP bonus, default: false}
  bonusxp.percent35.fishing: {description: 35% mcMMO XP bonus, default: false}
  bonusxp.percent35.herbalism: {description: 35% mcMMO XP bonus, default: false}
  bonusxp.percent35.mining: {description: 35% mcMMO XP bonus, default: false}
  bonusxp.percent35.repair: {description: 35% mcMMO XP bonus, default: false}
  bonusxp.percent35.smelting: {description: 35% mcMMO XP bonus, default: false}
  bonusxp.percent35.swords: {description: 35% mcMMO XP bonus, default: false}
  bonusxp.percent35.taming: {description: 35% mcMMO XP bonus, default: false}
  bonusxp.percent35.unarmed: {description: 35% mcMMO XP bonus, default: false}
  bonusxp.percent35.woodcutting: {description: 35% mcMMO XP bonus, default: false}
  bonusxp.percent40.acrobatics: {description: 40% mcMMO XP bonus, default: false}
  bonusxp.percent40.archery: {description: 40% mcMMO XP bonus, default: false}
  bonusxp.percent40.axes: {description: 40% mcMMO XP bonus, default: false}
  bonusxp.percent40.excavation: {description: 40% mcMMO XP bonus, default: false}
  bonusxp.percent40.fishing: {description: 40% mcMMO XP bonus, default: false}
  bonusxp.percent40.herbalism: {description: 40% mcMMO XP bonus, default: false}
  bonusxp.percent40.mining: {description: 40% mcMMO XP bonus, default: false}
  bonusxp.percent40.repair: {description: 40% mcMMO XP bonus, default: false}
  bonusxp.percent40.smelting: {description: 40% mcMMO XP bonus, default: false}
  bonusxp.percent40.swords: {description: 40% mcMMO XP bonus, default: false}
  bonusxp.percent40.taming: {description: 40% mcMMO XP bonus, default: false}
  bonusxp.percent40.unarmed: {description: 40% mcMMO XP bonus, default: false}
  bonusxp.percent40.woodcutting: {description: 40% mcMMO XP bonus, default: false}
  bonusxp.percent45.acrobatics: {description: 45% mcMMO XP bonus, default: false}
  bonusxp.percent45.archery: {description: 45% mcMMO XP bonus, default: false}
  bonusxp.percent45.axes: {description: 45% mcMMO XP bonus, default: false}
  bonusxp.percent45.excavation: {description: 45% mcMMO XP bonus, default: false}
  bonusxp.percent45.fishing: {description: 45% mcMMO XP bonus, default: false}
  bonusxp.percent45.herbalism: {description: 45% mcMMO XP bonus, default: false}
  bonusxp.percent45.mining: {description: 45% mcMMO XP bonus, default: false}
  bonusxp.percent45.repair: {description: 45% mcMMO XP bonus, default: false}
  bonusxp.percent45.smelting: {description: 45% mcMMO XP bonus, default: false}
  bonusxp.percent45.swords: {description: 45% mcMMO XP bonus, default: false}
  bonusxp.percent45.taming: {description: 45% mcMMO XP bonus, default: false}
  bonusxp.percent45.unarmed: {description: 45% mcMMO XP bonus, default: false}
  bonusxp.percent45.woodcutting: {description: 45% mcMMO XP bonus, default: false}
# -------------------------------------------- #
# STAR NOTATION
# -------------------------------------------- #
  bonusxp.percent5.*: 
    default: false
    description: implies access to all 5% mcMMO XP bonusses
    children:
      bonusxp.percent5.acrobatics: true
      bonusxp.percent5.archery: true
      bonusxp.percent5.axes: true
      bonusxp.percent5.excavation: true
      bonusxp.percent5.fishing: true
      bonusxp.percent5.herbalism: true
      bonusxp.percent5.mining: true
      bonusxp.percent5.repair: true
      bonusxp.percent5.smelting: true
      bonusxp.percent5.swords: true
      bonusxp.percent5.taming: true
      bonusxp.percent5.unarmed: true
      bonusxp.percent5.woodcutting: true

  bonusxp.percent10.*: 
    default: false
    description: implies access to all 10% mcMMO XP bonusses
    children:
      bonusxp.percent10.acrobatics: true
      bonusxp.percent10.archery: true
      bonusxp.percent10.axes: true
      bonusxp.percent10.excavation: true
      bonusxp.percent10.fishing: true
      bonusxp.percent10.herbalism: true
      bonusxp.percent10.mining: true
      bonusxp.percent10.repair: true
      bonusxp.percent10.smelting: true
      bonusxp.percent10.swords: true
      bonusxp.percent10.taming: true
      bonusxp.percent10.unarmed: true
      bonusxp.percent10.woodcutting: true

  bonusxp.percent15.*: 
    default: false
    description: implies access to all 15% mcMMO XP bonusses
    children:
      bonusxp.percent15.acrobatics: true
      bonusxp.percent15.archery: true
      bonusxp.percent15.axes: true
      bonusxp.percent15.excavation: true
      bonusxp.percent15.fishing: true
      bonusxp.percent15.herbalism: true
      bonusxp.percent15.mining: true
      bonusxp.percent15.repair: true
      bonusxp.percent15.smelting: true
      bonusxp.percent15.swords: true
      bonusxp.percent15.taming: true
      bonusxp.percent15.unarmed: true
      bonusxp.percent15.woodcutting: true

  bonusxp.percent20.*: 
    default: false
    description: implies access to all 20% mcMMO XP bonusses
    children:
      bonusxp.percent20.acrobatics: true
      bonusxp.percent20.archery: true
      bonusxp.percent20.axes: true
      bonusxp.percent20.excavation: true
      bonusxp.percent20.fishing: true
      bonusxp.percent20.herbalism: true
      bonusxp.percent20.mining: true
      bonusxp.percent20.repair: true
      bonusxp.percent20.smelting: true
      bonusxp.percent20.swords: true
      bonusxp.percent20.taming: true
      bonusxp.percent20.unarmed: true
      bonusxp.percent20.woodcutting: true

  bonusxp.percent25.*: 
    default: false
    description: implies access to all 25% mcMMO XP bonusses
    children:
      bonusxp.percent25.acrobatics: true
      bonusxp.percent25.archery: true
      bonusxp.percent25.axes: true
      bonusxp.percent25.excavation: true
      bonusxp.percent25.fishing: true
      bonusxp.percent25.herbalism: true
      bonusxp.percent25.mining: true
      bonusxp.percent25.repair: true
      bonusxp.percent25.smelting: true
      bonusxp.percent25.swords: true
      bonusxp.percent25.taming: true
      bonusxp.percent25.unarmed: true
      bonusxp.percent25.woodcutting: true

  bonusxp.percent30.*: 
    default: false
    description: implies access to all 30% mcMMO XP bonusses
    children:
      bonusxp.percent30.acrobatics: true
      bonusxp.percent30.archery: true
      bonusxp.percent30.axes: true
      bonusxp.percent30.excavation: true
      bonusxp.percent30.fishing: true
      bonusxp.percent30.herbalism: true
      bonusxp.percent30.mining: true
      bonusxp.percent30.repair: true
      bonusxp.percent30.smelting: true
      bonusxp.percent30.swords: true
      bonusxp.percent30.taming: true
      bonusxp.percent30.unarmed: true
      bonusxp.percent30.woodcutting: true

  bonusxp.percent35.*: 
    default: false
    description: implies access to all 35% mcMMO XP bonusses
    children:
      bonusxp.percent35.acrobatics: true
      bonusxp.percent35.archery: true
      bonusxp.percent35.axes: true
      bonusxp.percent35.excavation: true
      bonusxp.percent35.fishing: true
      bonusxp.percent35.herbalism: true
      bonusxp.percent35.mining: true
      bonusxp.percent35.repair: true
      bonusxp.percent35.smelting: true
      bonusxp.percent35.swords: true
      bonusxp.percent35.taming: true
      bonusxp.percent35.unarmed: true
      bonusxp.percent35.woodcutting: true

  bonusxp.percent40.*: 
    default: false
    description: implies access to all 40% mcMMO XP bonusses
    children:
      bonusxp.percent40.acrobatics: true
      bonusxp.percent40.archery: true
      bonusxp.percent40.axes: true
      bonusxp.percent40.excavation: true
      bonusxp.percent40.fishing: true
      bonusxp.percent40.herbalism: true
      bonusxp.percent40.mining: true
      bonusxp.percent40.repair: true
      bonusxp.percent40.smelting: true
      bonusxp.percent40.swords: true
      bonusxp.percent40.taming: true
      bonusxp.percent40.unarmed: true
      bonusxp.percent40.woodcutting: true

  bonusxp.percent45.*: 
    default: false
    description: implies access to all 45% mcMMO XP bonusses
    children:
      bonusxp.percent45.acrobatics: true
      bonusxp.percent45.archery: true
      bonusxp.percent45.axes: true
      bonusxp.percent45.excavation: true
      bonusxp.percent45.fishing: true
      bonusxp.percent45.herbalism: true
      bonusxp.percent45.mining: true
      bonusxp.percent45.repair: true
      bonusxp.percent45.smelting: true
      bonusxp.percent45.swords: true
      bonusxp.percent45.taming: true
      bonusxp.percent45.unarmed: true
      bonusxp.percent45.woodcutting: true